# docker-compose.yml

version: '3.10'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    depends_on:
      - mysql
    ports:
      - 80:8000
    volumes:
      - ./:/code
    command: bash -c 'uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'